# -*- coding: utf-8 -*-
"""pipeline_singlepage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18K0eut-zW0oseOBnrH-vetMsil3Fidyn

## SETUP

Monto Google Drive e definisco i percorsi dei file (annotazioni, immagini,
benchmark, predizioni) e i parametri di bilanciamento del benchmark: quante
domande corrompo per ciascun tipo (entity, element, layout) e quante ne tengo
clean, per arrivare a un totale di 200 campioni bilanciati 50/50.
"""

# ══ SETUP GLOBALE ══


from google.colab import drive
drive.mount('/content/drive')

import json, os, re, random, tarfile, gc
from collections import Counter, defaultdict

SEED = 42
random.seed(SEED)

# ── Percorsi ──
DRIVE_DIR  = '/content/drive/MyDrive/docvqa'
QAS_DIR    = f'{DRIVE_DIR}/spdocvqa_qas'
TAR_PATH   = f'{DRIVE_DIR}/spdocvqa_images/spdocvqa_images.tar.gz'
IMG_DIR    = '/content/spdocvqa_images'
BENCH_PATH = f'{DRIVE_DIR}/benchmark_final.json'
PRED_DIR   = f'{DRIVE_DIR}/predictions'          # predizioni persistite qui
os.makedirs(PRED_DIR, exist_ok=True)

# Bilanciamento ragionevole
N_ENTITY  = 34   # ~33% delle corrotte
N_ELEMENT = 33   # ~33% delle corrotte
N_LAYOUT  = 33   # ~33% delle corrotte
N_CLEAN   = 100  # 50/50 con le corrotte

# Totale: 100 corrotte + 100 clean = 200 campioni

"""## CARICAMENTO DATI

Carico le annotazioni originali di SP-DocVQA (train + validation) e le unisco
in un unico pool. Ispeziono un campione per capire la struttura dei dati e i
question_types disponibili, che userò per il campionamento stratificato.
"""

# ──  Caricamento annotazioni SP-DocVQA (train + val) ──

#caricamento train
with open(f'{QAS_DIR}/train_v1.0_withQT.json') as f:
    data_train = json.load(f)
#caricamento validation
with open(f'{QAS_DIR}/val_v1.0_withQT.json') as f:
    data_val = json.load(f)

#unisco i dataset
all_data = data_train['data'] + data_val['data']



print(f"Train: {len(data_train['data'])} | Val: {len(data_val['data'])} | Totale: {len(all_data)}")


print("\nEsempio di campione:")
# Seleziona i campi che ci interessano dal primo campione
campi = ('questionId', 'question', 'question_types', 'image', 'answers')
esempio = {k: all_data[0][k] for k in campi}

# Stampa in modo leggibile
print(json.dumps(esempio, indent=2))

print("\nQuestion types:", sorted({t for s in all_data for t in s['question_types']}))

"""## PARTE 1 — CORRUPTION ENGINE

Definisco le tre funzioni di corruzione (corrupt_entity, corrupt_element,
corrupt_layout). Regola fondamentale per tutte e tre: la domanda corrotta
resta grammaticalmente corretta, l'unanswerability si scopre SOLO guardando
l'immagine del documento, mai per un problema linguistico nella domanda.

- **entity**: sostituisco un'entità riconosciuta da spaCy NER (data, luogo,
  persona, importo...) con un'altra dello stesso tipo, assente dal documento.
- **element**: sostituisco il riferimento a un elemento di pagina (tabella,
  figura, footnote...) con uno di un gruppo semanticamente diverso.
- **layout**: sostituisco un riferimento di posizione (es. "in alto a
  sinistra") con il suo opposto.
"""

# ── Corruption Engine ──


# Regola fondamentale: la corruzione rende l'informazione richiesta ASSENTE dal documento.
# La domanda rimane grammaticalmente corretta, l'unanswerability si scopre SOLO guardando l'immagine.

import spacy

# Carica il modello NLP di spaCy per riconoscere le entità nelle domande (date, luoghi, ecc.)
# Se non è installato, lo scarica automaticamente.
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    import subprocess
    subprocess.run(["python", "-m", "spacy", "download", "en_core_web_sm"], check=True)
    nlp = spacy.load("en_core_web_sm")

########################################   ENTITY    ####################################
ENTITY_POOLS = {
    "DATE":     ["March 2027", "1965", "April 12, 2031", "the year 2044",
                 "September 1958", "February 2003", "July 1999", "October 2015"],
    "GPE":      ["Reykjavik", "Montevideo", "Tashkent", "Wellington",
                 "Nairobi", "Bratislava", "Ulaanbaatar"],
    "LOC":      ["the Andes", "the Baltic Sea", "the Sahara", "the Pyrenees", "the Gobi Desert"],
    "ORG":      ["Zentech Holdings", "Marwick & Vale", "the Halverson Institute",
                 "Penrose Corp", "Valtrade Group", "Nordex Solutions"],
    "PERSON":   ["Eleanor Whitfield", "Marcus Delgado", "Priya Ramachandran",
                 "Tobias Lindqvist", "Fatima Al-Rashid", "Chen Wei"],
    "CARDINAL": ["847", "13", "2,915", "66", "1,204", "342", "7,800", "29"],
    "MONEY":    ["$3,720", "$48.50", "$192,000", "$7.25", "$5,430", "$0.99"],
    "PERCENT":  ["73%", "12.4%", "5%", "88%", "31%", "6.7%"],
    "ORDINAL":  ["seventh", "twenty-third", "ninth", "fifteenth", "fourth"],
    "TIME":     ["3:45 PM", "11:20 AM", "midnight", "6:00 AM", "9:30 PM"],
    "QUANTITY": ["12 kilometers", "3.5 liters", "80 kg", "450 grams", "2.3 miles"],
}


# Parole interrogative: evita di sostituire "when" o "what" scambiandoli per entità
INTERROGATIVE = {"which", "what", "when", "how", "where", "who", "many", "much"}

# Numeri generici che spaCy classifica come CARDINAL ma non sono entità significative
# Es: "one table", "few rows",  sostituirli non renderebbe la domanda unanswerable
CARDINAL_BLACKLIST = {
    "one", "two", "three", "four", "five", "six", "seven", "eight",
    "nine", "ten", "few", "many", "several", "some", "any", "no"
}

# Pattern da escludere:
# - "year-old" / "years-old": età, non date (es. "a 5 year-old company")
# - r"^[A-Z]{2,5}$": acronimi puri come "USA", "CEO" — spaCy li vede come ORG ma non sono sostituibili
BLACKLIST_PATTERNS = ["year-old", "years-old", r"^[A-Z]{2,5}$"]



def blacklisted(text):
    """
    Restituisce True se l'entità NON deve essere sostituita.
    Controlla due casi:
      - pattern regex (iniziano con ^): es. acronimi come "USA", "CEO"
      - sottostringa semplice: es. "year-old" dentro "5 year-old company"
    """
    for pattern in BLACKLIST_PATTERNS:
        if pattern.startswith("^"):
            # È un pattern regex: controlla se il testo corrisponde esattamente
            if re.match(pattern, text):
                return True
        else:
            # È una parola semplice: controlla se compare nel testo
            if pattern in text.lower():
                return True
    return False


def entity_candidates(doc):
    """
    Restituisce la lista delle entità della domanda che possono essere sostituite.
    Un'entità è candidata solo se supera tutti e 4 i filtri:
    """
    candidates = []

    for ent in doc.ents:

        # 1) Il tipo di entità deve essere tra quelli che sappiamo sostituire
        if ent.label_ not in ENTITY_POOLS:
            continue

        # 2) La prima parola non deve essere interrogativa (es. "what", "when")
        #    spaCy a volte classifica queste parole come entità per errore
        if ent.text.split()[0].lower() in INTERROGATIVE:
            continue

        # 3) Il testo non deve essere in blacklist (acronimi, età, ecc.)
        if blacklisted(ent.text):
            continue

        # 4) I CARDINAL generici ("one", "few", "many"...) non sono entità significative
        if ent.label_ == "CARDINAL" and ent.text.lower() in CARDINAL_BLACKLIST:
            continue

        candidates.append(ent)

    return candidates

def corrupt_entity(question, doc=None):
    """
    Sostituisce una entità nella domanda con un valore diverso dello stesso tipo.
    Restituisce (domanda_corrotta, descrizione_della_modifica) oppure None se non è possibile.
    """

    # Analizza la domanda con spaCy (se non è già stata analizzata)
    if doc is None:
        doc = nlp(question)

    # Trova le entità sostituibili
    candidates = entity_candidates(doc)
    if not candidates:
        return None

    # Sceglie una entità a caso tra i candidati
    ent = random.choice(candidates)

# Prende i valori del pool escludendo il valore originale
    # (per evitare di "sostituire" con la stessa cosa)
    pool = []
    for v in ENTITY_POOLS[ent.label_]:
        if v.lower() != ent.text.lower():
            pool.append(v)

    # Se il pool è vuoto non si può corrompere
    if not pool:
        return None

# Controllo di sicurezza: il carattere subito dopo l'entità deve essere
    # uno spazio o punteggiatura, altrimenti la sostituzione produrrebbe
    # una parola "incollata" al testo successivo (es. "2019report")

    # Se l'entità è l'ultima parola della domanda, non c'è nessun carattere dopo
    if ent.end_char < len(question):
        char_after_entity = question[ent.end_char]
    else:
        char_after_entity = " "  # spazio fittizio: nessun problema di incollamento

    if char_after_entity not in " .,;:?!\n)'\"":
        return None


    # Sostituisce l'entità originale con il nuovo valore
    new_val = random.choice(pool)
    corrupted_question = question[:ent.start_char] + new_val + question[ent.end_char:]

    # Descrizione della modifica (utile per il debug e la relazione)
    detail = f"{ent.text} ({ent.label_}) -> {new_val}"

    return corrupted_question, detail


    ########################################   ELEMENTS    ####################################



# ELEMENT: gruppi semanticamente lontani. Sostituire tra gruppi DIVERSI riduce il rischio
# che l'elemento sostitutivo sia comunque presente nella pagina (label noise).
ELEMENT_GROUPS = [
    ["table", "row", "column", "sheet", "field"],  # elementi tabulari
    ["figure", "chart", "graph", "diagram"],       # elementi visivi
    ["footnote", "caption", "header", "heading", "section"],  # elementi testuali
]
# Lista piatta di tutti gli elementi di pagina (tutti i gruppi uniti in una lista sola)
ELEMENTS = []
for group in ELEMENT_GROUPS:
    for element in group:
        ELEMENTS.append(element)





def corrupt_element(question):
    # Trova tutti gli elementi di pagina presenti nella domanda
    found = []
    for element in ELEMENTS:
        if re.search(rf"\b{element}\b", question, re.I):
            found.append(element)

    if not found:
        return None

    # Sceglie a caso quale elemento sostituire
    target = random.choice(found)

    # Raccoglie tutti gli elementi di gruppi DIVERSI da quello del target
    other_group_elements = []
    for group in ELEMENT_GROUPS:
        if target not in group:
            other_group_elements.extend(group)

    replacement = random.choice(other_group_elements)

    corrupted_question = re.sub(rf"\b{target}\b", replacement, question, count=1, flags=re.I)
    detail = f"{target} -> {replacement}"
    return corrupted_question, detail

    ########################################   LAYOUT    ####################################


# LAYOUT: opposti spaziali + posizioni ordinali legate a nomi strutturali
LAYOUT_OPPOSITES = {
    "top left": ["bottom right"], "top right": ["bottom left"],
    "bottom left": ["top right"], "bottom right": ["top left"],
    "upper left": ["lower right"], "upper right": ["lower left"],
    "lower left": ["upper right"], "lower right": ["upper left"],
    "top": ["bottom"], "bottom": ["top"], "left": ["right"], "right": ["left"],
    "upper": ["lower"], "lower": ["upper"], "above": ["below"], "below": ["above"],
    "corner": ["center"],
}
POSITIONAL  = {"first": ["last","third"], "last": ["first","third"],
               "second": ["last","first"], "third": ["first","last"]}
STRUCT_NOUN = r"(row|column|page|section|paragraph|line|item|entry|table|figure)"

def corrupt_layout(question):
    """
    Sostituisce un riferimento spaziale o ordinale nella domanda con il suo opposto.
    Restituisce (domanda_corrotta, descrizione) oppure None se non trova nulla da corrompere.
    """
    q = question.lower()

    # ── Parte 1: termini spaziali (top, bottom, left, right, ecc.) ──
    # Scorre dal più lungo al più corto per trovare prima "top left" rispetto a "top"
    for term in sorted(LAYOUT_OPPOSITES, key=len, reverse=True):
        term_escaped = re.escape(term)

        # Il termine deve essere seguito da una parola strutturale del documento
        # per escludere usi generici come "top priority" o "left alone"
        is_position_reference = re.search(
            rf"\b{term_escaped}\s+(the\s+)?(of|corner|part|side|margin|page|section|table|figure)\b", q
        )

        if is_position_reference:
            replacement = random.choice(LAYOUT_OPPOSITES[term])
            corrupted_question = re.sub(rf"\b{term_escaped}\b", replacement, question, count=1, flags=re.I)
            detail = f"{term} -> {replacement}"
            return corrupted_question, detail

    # ── Parte 2: posizioni ordinali + nome strutturale (es. "first row", "last column") ──
    for word, alternatives in POSITIONAL.items():
        if re.search(rf"\b{word}\b\s+{STRUCT_NOUN}", q):
            replacement = random.choice(alternatives)
            corrupted_question = re.sub(rf"\b{word}\b", replacement, question, count=1, flags=re.I)
            detail = f"{word} -> {replacement}"
            return corrupted_question, detail

    return None

# Dizionario che mappa ogni tipo di corruzione alla sua funzione
CORRUPTORS = {
    "entity":  corrupt_entity,
    "element": corrupt_element,
    "layout":  corrupt_layout,
}

"""## CORRUZIONE + CAMPIONAMENTO + SETUP CLEAN

Applico le tre funzioni di corruzione con campionamento stratificato per
question_type, per coprire in modo bilanciato tutte le tipologie di domanda.
In parallelo campiono le domande "clean" (answerable), escludendo quelle già
usate come corrotte, per arrivare a 200 campioni totali, 50/50.
"""

# ── Pool di candidati, campionamento stratificato e applicazione delle corruzioni ──
random.seed(SEED)

# Estrae tutte le domande in una lista (serve a nlp.pipe per analizzarle in batch)
questions = [s["question"] for s in all_data]

# Pool di candidati per ogni tipo di corruzione
pools = {
    "entity":  [],
    "element": [],
    "layout":  []
}

# Analizza tutte le domande in batch con spaCy e costruisce i pool
for doc, s in zip(nlp.pipe(questions, batch_size=512), all_data):
    if entity_candidates(doc):
        pools["entity"].append(s)
    if corrupt_element(s["question"]):
        pools["element"].append(s)
    if corrupt_layout(s["question"]):
        pools["layout"].append(s)

print("Domande corrompibili per tipo:", {k: len(v) for k, v in pools.items()})

# Insiemi per evitare duplicati nel benchmark finale
used_qids      = set()  # tiene traccia degli id già usati
seen_questions = set()  # tiene traccia delle domande già viste


def sample_and_corrupt(pool, ctype, n):
    """
    Campiona n domande dal pool, le corrompe e le restituisce come record per il benchmark.
    Il campionamento è stratificato per question_type per rappresentare tutti i tipi di domanda.
    """

    corruption_fn = CORRUPTORS[ctype]

    # Raggruppa le domande per question_type
    by_type = defaultdict(list)
    for s in pool:
        by_type[s['question_types'][0]].append(s)

    # Quota uniforme per tipo: es. n=17, 4 tipi → 4 per tipo
    quota = max(1, n // len(by_type))
    records = []

    def try_add(s):
        # Normalizza per il controllo duplicati
        question_normalized = re.sub(r'\s+', ' ', s['question'].lower().strip())

        # Scarta duplicati
        if s['questionId'] in used_qids or question_normalized in seen_questions:
            return False

        # Prova a corrompere
        result = corruption_fn(s["question"])
        if result is None:
            return False

        corrupted_question, detail = result

        # Registra come usata
        used_qids.add(s['questionId'])
        seen_questions.add(question_normalized)

        # Costruisce e aggiunge il record
        records.append({
            **s,
            "question":          corrupted_question,
            "original_question": s["question"],
            "corruption_type":   ctype,
            "corruption_detail": detail,
            "label":             "unanswerable"
        })
        return True

    # Prima passa: quota uniforme per question_type
    for question_type, samples in by_type.items():
        added = 0
        for s in random.sample(samples, len(samples)):
            if added == quota or len(records) == n:
                break
            if try_add(s):
                added += 1

    # Seconda passa: riempie i posti rimasti scorrendo tutto il pool
    for s in random.sample(pool, len(pool)):
        if len(records) == n:
            break
        try_add(s)

    return records


# Applica le corruzioni ai tre pool e unisce i risultati in una lista unica
entity_data  = sample_and_corrupt(pools["entity"],  "entity",  N_ENTITY)
element_data = sample_and_corrupt(pools["element"], "element", N_ELEMENT)
layout_data  = sample_and_corrupt(pools["layout"],  "layout",  N_LAYOUT)

corrupted_data = entity_data + element_data + layout_data

# Controllo: verifica che ogni pool abbia prodotto il numero atteso di campioni
n_entity  = len([d for d in corrupted_data if d['corruption_type'] == 'entity'])
n_element = len([d for d in corrupted_data if d['corruption_type'] == 'element'])
n_layout  = len([d for d in corrupted_data if d['corruption_type'] == 'layout'])

print(f"Entity:  {n_entity}/{N_ENTITY}")
print(f"Element: {n_element}/{N_ELEMENT}")
print(f"Layout:  {n_layout}/{N_LAYOUT}")




# ── Campionamento delle domande clean (answerable) ──

# Esclude le domande già usate per le corruzioni
# (evita che la stessa domanda appaia sia come corrotta che come clean)
clean_pool = []
for s in all_data:
    if s['questionId'] not in used_qids:
        clean_pool.append(s)



# Raggruppa per question_type
by_type = defaultdict(list)
for s in clean_pool:
    by_type[s['question_types'][0]].append(s)

# Prima passa: quota uniforme per question_type
clean_data = []
quota = N_CLEAN // len(by_type)
for question_type, samples in by_type.items():
    n_to_take = min(quota, len(samples))
    clean_data += random.sample(samples, n_to_take)

# Seconda passa: riempie i posti rimasti (con fix anti-crash)
already_used = {c['questionId'] for c in clean_data}
extra_pool   = [s for s in clean_pool if s['questionId'] not in already_used]
remaining    = N_CLEAN - len(clean_data)
clean_data  += random.sample(extra_pool, min(remaining, len(extra_pool)))

# Aggiunge le etichette per la classificazione
clean_data = [
    {**s, "label": "answerable", "corruption_type": "clean"}
    for s in clean_data
]

# ── Riepilogo ──
print(f"\nCorrotte: {len(corrupted_data)} | Clean: {len(clean_data)}")
print("Distribuzione corruzioni:", dict(Counter(d['corruption_type'] for d in corrupted_data)))

# Mostra un esempio per ogni tipo di corruzione
for ctype in ["entity", "element", "layout"]:
    esempio = next(d for d in corrupted_data if d["corruption_type"] == ctype)
    print(f"\n[{ctype}]")
    print(f"  Originale : {esempio['original_question']}")
    print(f"  Corrotta  : {esempio['question']}")
    print(f"  Modifica  : {esempio['corruption_detail']}")

"""## LLM AS A JUDGE


Verifica qualità con LLM-as-a-judge
Il judge (LLaMA-3.3-70B via Groq) è volutamente text-only, non vede l'immagine: una corruzione è valida solo se

- well_formed : la domanda è grammaticalmente corretta e naturale;
- needs_document : dal solo testo è impossibile capire che è unanswerable → serve ispezionare il documento.
Se un criterio fallisce, la domanda viene riscritta automaticamente (max 1 tentativo) e ri-giudicata. Nessun fix manuale.
"""

# ── LLM-as-a-judge (Groq, llama-3.3-70b) ──
!pip install groq -q

from groq import Groq
from google.colab import userdata
import time

# Inizializza il client Groq con la chiave API
groq_client = Groq(api_key=userdata.get("GROQ_API_KEY"))

# ── Prompt di sistema: ruolo del judge ──
JUDGE_SYSTEM = "You are an expert annotator for document question answering benchmarks."

# ── Prompt di valutazione ──
# Il judge valuta la domanda corrotta su due criteri:
#   1. well_formed     → la domanda è grammaticalmente corretta e naturale
#   2. needs_document  → dal solo testo non si capisce che è unanswerable,
#                        bisogna guardare l'immagine del documento
JUDGE_PROMPT = """
Original question:  {orig}
Corrupted question: {corr}
Corruption type:    {ctype}

The corrupted question will be shown to a vision model together with a document image.
Evaluate it on two criteria:

1. well_formed: the question is grammatically correct and reads naturally.
2. needs_document: from the text alone it is impossible to tell the question is
   unanswerable — one must look at the document image to find out.

Reply ONLY with this JSON:
{{"well_formed": true, "needs_document": true, "reason": "..."}}
"""


# ── Prompt di riscrittura ──
# Se la domanda fallisce uno dei criteri, il judge prova a riscriverla
# mantenendo la corruzione ma migliorando forma e naturalezza
REWRITE_PROMPT = """
Original question:  {orig}
Corrupted question: {corr}
Corruption type:    {ctype}
Problem:            {reason}

Rewrite the corrupted question so that:
- it is grammatically correct and natural
- it PRESERVES the corruption (do not restore the original value)
- its unanswerability can only be verified by looking at the document image

Reply ONLY with this JSON:
{{"rewritten_question": "..."}}
"""


def call_api(messages, max_tokens=200, max_retries=3):
    """
    Chiama l'API di Groq e restituisce il testo della risposta.
    Se riceve un errore di rate limit (429), aspetta e riprova.
    """
    for attempt in range(max_retries):
        try:
            response = groq_client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=messages,
                max_tokens=max_tokens,
                temperature=0.0
            )
            return response.choices[0].message.content

        except Exception as e:
            if "429" in str(e):
                wait_seconds = 10 * (attempt + 1)
                print(f"Rate limit raggiunto, aspetto {wait_seconds}s...")
                time.sleep(wait_seconds)
            else:
                raise

    return None


def extract_json(text):
    """
    Estrae il primo oggetto JSON dalla risposta del judge.
    Restituisce None se non trova JSON valido.
    """
    match = re.search(r"\{.*\}", text or "", re.S)
    if match is None:
        return None
    try:
        return json.loads(match.group())
    except json.JSONDecodeError:
        return None


def evaluate(sample, question):
    """
    Chiede al judge di valutare la domanda corrotta.
    Restituisce un dizionario con well_formed, needs_document e reason.
    """
    messages = [
        {"role": "system", "content": JUDGE_SYSTEM},
        {"role": "user",   "content": JUDGE_PROMPT.format(
            orig  = sample["original_question"],
            corr  = question,
            ctype = sample["corruption_type"]
        )}
    ]

    raw_response = call_api(messages)
    result = extract_json(raw_response)

    if result is None:
        return {"well_formed": None, "needs_document": None, "reason": "PARSE_FAIL"}

    return result


def rewrite(sample, question, reason):
    """
    Chiede al judge di riscrivere la domanda che non ha superato la valutazione.
    Restituisce la domanda riscritta oppure None se la riscrittura fallisce.
    """
    messages = [
        {"role": "system", "content": JUDGE_SYSTEM},
        {"role": "user",   "content": REWRITE_PROMPT.format(
            orig   = sample["original_question"],
            corr   = question,
            ctype  = sample["corruption_type"],
            reason = reason
        )}
    ]

    raw_response = call_api(messages)
    result = extract_json(raw_response)

    if result is None:
        return None

    return result.get("rewritten_question")


def is_valid(verdict):
    """
    Restituisce True se la domanda ha superato entrambi i criteri del judge.
    """
    return verdict.get("well_formed") is True and verdict.get("needs_document") is True


# ── Valutazione di ogni domanda corrotta ──
MAX_REWRITES = 1  # al massimo 1 tentativo di riscrittura per domanda

for i, sample in enumerate(corrupted_data):

    current_question = sample["question"]
    n_rewrites = 0

    # Valutazione iniziale
    verdict = evaluate(sample, current_question)

    # Se non valida, prova a riscrivere una volta
    if not is_valid(verdict) and n_rewrites < MAX_REWRITES:
        rewritten = rewrite(sample, current_question, verdict.get("reason", ""))
        n_rewrites += 1

        if rewritten is not None:
            current_question = rewritten
            verdict = evaluate(sample, current_question)

    # Salva la domanda finale nel record
    if current_question != sample["question"]:
        sample["question_before_rewrite"] = sample["question"]
        sample["question"] = current_question

    # Salva il verdetto nel record
    sample["n_rewrites"]    = n_rewrites
    sample["judge_verdict"] = "KEEP" if is_valid(verdict) else "REJECT"
    sample["judge_reason"]  = verdict.get("reason", "")

    # Stampa il progresso
    tag = f"R{n_rewrites}" if n_rewrites > 0 else "  "
    print(f"[{i+1:02d}/{len(corrupted_data)}] {tag} {sample['judge_verdict']:6s} "
          f"({sample['corruption_type']}) {current_question[:60]}")

# Conta quanti KEEP e quanti REJECT
conteggio_verdetti = Counter(s['judge_verdict'] for s in corrupted_data)

print("\nVerdetti finali:")
print(f"  KEEP   : {conteggio_verdetti['KEEP']}")
print(f"  REJECT : {conteggio_verdetti['REJECT']}")

"""## BILANCIAMENTO E SALVATAGGIO SU DRIVE

Tengo solo le domande corrotte approvate dal judge (verdict KEEP) e rimuovo
altrettante domande clean per mantenere il bilanciamento 50/50. Salvo il
benchmark finale su Drive (benchmark_final.json) ed estraggo dal tar solo le
immagini effettivamente necessarie. Faccio anche un check visivo: mostro
alcuni esempi corrotti affiancati all'immagine del documento, per verificare
manualmente che siano davvero unanswerable.
"""

# ──  Bilanciamento e salvataggio del benchmark su Drive ──
random.seed(SEED)

# Tiene solo le domande approvate dal judge
corrupted_keep = [d for d in corrupted_data if d["judge_verdict"] == "KEEP"]
n_reject       = len(corrupted_data) - len(corrupted_keep)

# Rimuove altrettante clean per mantenere il bilanciamento 50/50
# Esempio: 5 REJECT → rimuove 5 clean → rimane sempre metà corrotte, metà clean
if n_reject > 0:
    clean_data = random.sample(clean_data, len(clean_data) - n_reject)

# Unisce corrotte e clean, mescola per non averle in ordine
benchmark_final = corrupted_keep + clean_data
random.shuffle(benchmark_final)

# Salva il benchmark su Drive (sovrascrive se esiste già)
with open(BENCH_PATH, "w") as f:
    json.dump(benchmark_final, f, indent=2)

print(f"Benchmark salvato in: {BENCH_PATH}")
print(f"  Unanswerable : {len(corrupted_keep)}")
print(f"  Answerable   : {len(clean_data)}")
print(f"  Totale       : {len(benchmark_final)}")

# ──  Estrazione delle immagini del benchmark dal file tar ──
# Le immagini sono compresse in un unico file .tar.gz su Drive.
# Estraiamo SOLO le immagini che servono al benchmark (non tutte le 44812).

os.makedirs(IMG_DIR, exist_ok=True)

# Costruisce l'insieme dei nomi file delle immagini necessarie
# es. "documents/xnbl0037_1.png" → "xnbl0037_1.png"
needed = set()
for s in benchmark_final:
    filename = s['image'].replace('documents/', '')
    needed.add(filename)

# Controlla quali immagini mancano già in IMG_DIR
missing = set()
for filename in needed:
    full_path = os.path.join(IMG_DIR, filename)
    if not os.path.isfile(full_path):
        missing.add(filename)

# Estrae solo le immagini mancanti dal tar
if missing:
    with tarfile.open(TAR_PATH, 'r:gz') as tar:
        for member in tar.getmembers():
            if member.name in missing:
                tar.extract(member, path=IMG_DIR, filter='data')

# Riepilogo
n_already_present = len(needed) - len(missing)
print(f"Immagini necessarie : {len(needed)}")
print(f"  già presenti      : {n_already_present}")
print(f"  estratte ora      : {len(missing)}")

# ──  Verifica visiva delle corruzioni (spot-check contro l'immagine) ──
# Mostra 6 esempi per ogni tipo di corruzione affiancati all'immagine del documento.
# Serve per verificare manualmente che la domanda corrotta sia davvero unanswerable.

from PIL import Image
import matplotlib.pyplot as plt
import textwrap

def wrap(text, width=45):
    """Spezza il testo in righe da massimo width caratteri."""
    return "\n".join(textwrap.wrap(text, width))

def show_grid(corruption_type, n=6):
    """
    Mostra una griglia 2x3 con le immagini dei documenti e le domande corrotte.
    Per ogni immagine mostra: domanda originale, domanda corrotta, dettaglio modifica.
    """

    # Prende i primi n campioni del tipo richiesto
    samples = [d for d in corrupted_keep if d["corruption_type"] == corruption_type][:n]

    # Crea la griglia : altezza maggiore per ospitare le domande complete
    fig, axes = plt.subplots(2, 3, figsize=(18, 16))
    fig.suptitle(f"Spot-check: {corruption_type.upper()}", fontweight='bold', fontsize=14)

    for ax, sample in zip(axes.flat, samples):

        # Carica e mostra l'immagine del documento
        image_path = os.path.join(IMG_DIR, sample['image'].replace('documents/', ''))
        image = Image.open(image_path).convert('RGB')
        ax.imshow(image)
        ax.axis('off')

        # Mostra domanda originale, corrotta e dettaglio, con a capo automatico
        ax.set_title(
            f"ORI: {wrap(sample['original_question'])}\n"
            f"\nCOR: {wrap(sample['question'])}\n"
            f"\nMOD: {wrap(sample['corruption_detail'])}",
            fontsize=7,
            loc='left'  # allinea a sinistra per leggibilità
        )

    plt.tight_layout()
    plt.show()


# Mostra lo spot-check per tutti e tre i tipi di corruzione
for corruption_type in ["entity", "element", "layout"]:
    show_grid(corruption_type)

# Mostra il motivo del rigetto per le domande scartate dal judge
rejected = [s for s in corrupted_data if s["judge_verdict"] == "REJECT"]

print(f"Domande rifiutate: {len(rejected)}")
print()

for s in rejected:
    print(f"Tipo       : {s['corruption_type']}")
    print(f"Originale  : {s['original_question']}")
    print(f"Corrotta   : {s['question']}")
    print(f"Modifica   : {s['corruption_detail']}")
    print(f"Motivo     : {s['judge_reason']}")
    print()

# ── Caricamento benchmark da Drive ──

with open(BENCH_PATH) as f:
    benchmark_final = json.load(f)

# Ricostruisce le variabili necessarie per le celle successive
corrupted_keep = [s for s in benchmark_final if s["label"] == "unanswerable"]
clean_data     = [s for s in benchmark_final if s["label"] == "answerable"]

print(f"Benchmark caricato: {len(benchmark_final)} campioni")
print(f"  Unanswerable : {len(corrupted_keep)}")
print(f"  Answerable   : {len(clean_data)}")
print()

"""## PARTE 2 — INFERENZA BASELINE

Da qui parte l'inferenza vera e propria. Per ogni campione costruisco un
prompt SOLO testuale (domanda + istruzioni) e lo passo al modello insieme
all'immagine del documento: il modello deve guardare l'immagine per decidere
se la domanda è ANSWERABLE o UNANSWERABLE. Eseguo i tre VLM (Gemma, Qwen,
Phi) in sessioni Colab separate, perché richiedono versioni incompatibili
di transformers.
"""

from google.colab import drive
drive.mount('/content/drive')

import json, os, re, random, tarfile, gc
from collections import Counter, defaultdict
import torch
from PIL import Image

SEED = 42
random.seed(SEED)

# Percorsi
DRIVE_DIR  = '/content/drive/MyDrive/docvqa'
TAR_PATH   = f'{DRIVE_DIR}/spdocvqa_images/spdocvqa_images.tar.gz'
IMG_DIR    = '/content/spdocvqa_images'
BENCH_PATH = f'{DRIVE_DIR}/benchmark_final.json'
PRED_DIR   = f'{DRIVE_DIR}/predictions'
os.makedirs(PRED_DIR, exist_ok=True)

# Carica benchmark
with open(BENCH_PATH) as f:
    benchmark_final = json.load(f)
print(f"Benchmark: {len(benchmark_final)} campioni")

# Estrazione immagini (automatica ad ogni restart)
os.makedirs(IMG_DIR, exist_ok=True)
needed  = {s["image"].replace("documents/", "") for s in benchmark_final}
missing = {n for n in needed if not os.path.isfile(os.path.join(IMG_DIR, n))}
if missing:
    print(f"Estrazione {len(missing)} immagini dal tar...")
    with tarfile.open(TAR_PATH, "r:gz") as tar:
        for member in tar.getmembers():
            fname = os.path.basename(member.name)
            if fname in missing:
                member.name = fname
                tar.extract(member, IMG_DIR)
    print("Estrazione completata")
else:
    print(f"Immagini già presenti: {len(needed)}")

import torch
from PIL import Image

with open(BENCH_PATH) as f:
    benchmark_final = json.load(f)
print(f"Benchmark caricato da Drive: {len(benchmark_final)} campioni")


def resolve_image_path(image_field):
    """
    Converte il campo 'image' del benchmark nel path locale dell'immagine.

    Esempio:
        "documents/xnbl0037_1.png"  ->  "/content/spdocvqa_images/xnbl0037_1.png"
    """
    filename = image_field.replace("documents/", "")
    full_path = os.path.join(IMG_DIR, filename)

    if not os.path.isfile(full_path):
        raise FileNotFoundError(f"Immagine non trovata: {full_path}")

    return full_path

BASE_INSTRUCTION = (
    "You are a binary classifier. "
    "Look at the document image and decide whether "
    "the question can be answered using ONLY the information visible in the document."
)


# Template per ogni strategia di prompting
# Parte 2 → "baseline" | Parte 3 → "few_shot", "cot", "knowledge"

FEW_SHOT_EXAMPLES = """
Example 1:
Question: "What is the value shown in the bottom-left table?"
Reasoning: The document contains a table at the top-right, not bottom-left.
The referenced element does not exist in this position.
Answer: UNANSWERABLE

Example 2:
Question: "What is the total amount due?"
Reasoning: The document contains a row labeled 'Total Amount Due' with a value.
The information requested is present in the document.
Answer: ANSWERABLE
"""



KNOWLEDGE_NOTE = """Before answering, verify the following in the document image:
- Entities: check that any name, date, number, or organization mentioned
  in the question actually appears in the document.
- Elements: check that any referenced element (table, figure, chart, footnote)
  exists in the document.
- Layout: check that any referenced position (top, bottom, left, right)
  matches the actual position of elements in the document.

Only after this verification, answer with ANSWERABLE or UNANSWERABLE."""


COT_INSTRUCTION = """Think step by step:
1) What does the question ask for?
2) Is it visible in the document image?
   - YES → ANSWERABLE
   - NO  → UNANSWERABLE

Your last line must be exactly: ANSWERABLE or UNANSWERABLE."""



SYSTEM_MESSAGE = (
    "You are a binary classifier. "
    "You must reply with ONLY one word: ANSWERABLE or UNANSWERABLE. "
    "Never extract text from the document. Never answer the question itself."
)




def build_prompt(question, strategy="baseline"):
    if strategy == "baseline":
        return f"{BASE_INSTRUCTION}\n\nQuestion: {question}"

    if strategy == "few_shot":
        return f"{BASE_INSTRUCTION}\n\n{FEW_SHOT_EXAMPLES}\n\nQuestion: {question}"

    if strategy == "cot":
        return (
            f"Question: {question}\n\n"
            f"{COT_INSTRUCTION}"
        )

    if strategy == "knowledge":
        return f"{BASE_INSTRUCTION}\n\n{KNOWLEDGE_NOTE}\n\nQuestion: {question}"

    raise ValueError(f"Strategia sconosciuta: '{strategy}'")

def normalize_pred(raw):
    """
    Estrae la predizione finale dall'output grezzo del modello.
    Restituisce (predizione, parse_fail) dove parse_fail=True indica
    che il modello non ha prodotto una risposta conforme.

    Logica: vince l'ULTIMA occorrenza tra 'answerable' e 'unanswerable',
    perché i modelli CoT scrivono il ragionamento prima e la risposta alla fine.

    Caso tricky: 'unanswerable' contiene 'answerable' al suo interno
    (posizione iu+2), quindi va gestito esplicitamente.
    """
    text = (raw or "").lower()

    # Trova l'ultima occorrenza di ciascuna parola chiave
    pos_unanswerable = text.rfind("unanswerable")
    pos_answerable   = text.rfind("answerable")

    # Caso 1: nessuna parola chiave trovata -> output non conforme (es. modello estrattivo)
    if pos_unanswerable == -1 and pos_answerable == -1:
        return "answerable", True   # parse_fail=True: il modello non ha seguito le istruzioni

    # Caso 2: l'unico 'answerable' trovato è dentro 'unanswerable' (offset +2)
    if pos_unanswerable != -1 and pos_answerable == pos_unanswerable + 2:
        return "unanswerable", False

    # Caso 3: vince chi appare più tardi nel testo
    if pos_unanswerable > pos_answerable:
        return "unanswerable", False
    else:
        return "answerable", False


def run_inference(infer_fn, model_name, strategy="baseline"):
    """
    Orchestratore universale di inferenza.
    Gira su tutti i 200 campioni del benchmark e salva i risultati su Drive.

    Args:
        infer_fn   : funzione specifica del modello (infer_gemma, infer_qwen, ...)
        model_name : stringa identificativa per il nome del file JSON
        strategy   : "baseline" | "few_shot" | "cot" | "knowledge"
    """

    # CoT genera testo più lungo (ragionamento step-by-step)-> servono più token
    max_new_tokens = 64 if strategy == "cot" else 10

    results    = []
    fail_count = 0

    for i, sample in enumerate(benchmark_final):

        # Costruisce il prompt testuale per questo campione
        prompt = build_prompt(sample["question"], strategy)

        # Chiama il modello, in caso di errore registra stringa vuota e continua
        try:
            raw_output = infer_fn(
                resolve_image_path(sample["image"]),
                prompt,
                max_new_tokens
            )
        except Exception as e:
            print(f"[{model_name}] ERRORE campione {i}: {e}", flush=True)
            raw_output = ""

        # Normalizza l'output grezzo in ANSWERABLE / UNANSWERABLE
        prediction, parse_fail = normalize_pred(raw_output)
        fail_count += parse_fail

        # Salva il risultato per questo campione
        results.append({
            "id"             : sample["questionId"],
            "label"          : sample["label"],
            "prediction"     : prediction,
            "corruption_type": sample.get("corruption_type", "clean"),
            "question"       : sample["question"],
            "raw"            : raw_output.strip(),
            "parse_fail"     : parse_fail
        })

        # Stampa il progresso ogni 10 campioni
        if (i + 1) % 10 == 0:
            print(f"[{model_name} | {strategy}] {i+1}/{len(benchmark_final)}", flush=True)

    # Salva il JSON su Drive
    filename = f"predictions_{model_name}"
    if strategy != "baseline":
        filename += f"_{strategy}"

    output_path = os.path.join(PRED_DIR, f"{filename}.json")
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)

    print(f"\n[{model_name} | {strategy}] completato")
    print(f"  parse_fail : {fail_count}/{len(results)}")
    print(f"  salvato in : {output_path}")

    return results

def free_vram(*names):
    g = globals()
    for n in names:
        if n in g: del g[n]
    gc.collect(); torch.cuda.empty_cache()
    print(f"VRAM allocata: {torch.cuda.memory_allocated()/1e9:.2f} GB")

"""## GEMMA

Carico Gemma-3-4B-it e giro l'inferenza baseline sui 200 campioni.
"""

pip install "transformers>=4.50" -q

# ── Gemma-3-4B-it ──
# System message in formato lista (richiesto da Gemma pipeline).

from huggingface_hub import login
from google.colab import userdata
from transformers import pipeline

login(token=userdata.get('HF_TOKEN'))



pipe_gemma = pipeline(
    "image-text-to-text",
    model="google/gemma-3-4b-it",
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

def infer_gemma(image_path, prompt, max_new_tokens):
    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    messages = [
        # Gemma richiede il system message come lista di content
        {"role": "system", "content": [{"type": "text", "text": SYSTEM_MESSAGE}]},
        {"role": "user",   "content": [
            {"type": "image", "image": img},
            {"type": "text",  "text": prompt}
        ]}
    ]

    out = pipe_gemma(messages, max_new_tokens=max_new_tokens)
    return out[0]["generated_text"][-1]["content"]


predictions_gemma = run_inference(infer_gemma, "gemma3_4b")
free_vram("pipe_gemma")

"""## QWEN

Carico Qwen2-VL-2B-Instruct e giro l'inferenza baseline sugli stessi 200
campioni.
"""

pip install "transformers>=4.52" qwen-vl-utils -q

# ── Sessione B: Qwen2-VL-2B-Instruct ──
# → Runtime > Restart session → Setup globale → Utilities → questa cella

from transformers import Qwen2VLForConditionalGeneration, AutoProcessor

# Caricamento modello
qwen_model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    torch_dtype=torch.float16,
    device_map="auto"
)
qwen_proc = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct")


def infer_qwen(image_path, prompt, max_new_tokens):
    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    messages = [
        {"role": "system", "content": SYSTEM_MESSAGE},  # stessa variabile di Gemma
        {"role": "user", "content": [
            {"type": "image", "image": img},
            {"type": "text",  "text": prompt}
        ]}
    ]

    text   = qwen_proc.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = qwen_proc(text=[text], images=[img], return_tensors="pt").to(qwen_model.device)

    with torch.no_grad():
        output_ids = qwen_model.generate(**inputs, max_new_tokens=max_new_tokens)

    new_tokens = output_ids[0][inputs["input_ids"].shape[-1]:]
    return qwen_proc.decode(new_tokens, skip_special_tokens=True)




# Inferenza su tutti i 200 campioni → salva predictions_qwen2vl_2b.json su Drive
predictions_qwen = run_inference(infer_qwen, "qwen2vl_2b")

# Libera la VRAM prima della sessione successiva
free_vram("qwen_model", "qwen_proc")

"""## PHI 3.5

Sessione separata (transformers==4.48.0): carico Phi-3.5-vision-instruct e
giro l'inferenza baseline.
"""

pip install "transformers==4.48.0" -q

# ── Phi-3.5-vision-instruct ──
# Sessione separata: !pip install "transformers==4.48.0" -q
# → Runtime > Restart session → Setup globale → Utilities → questa cella
# Il system message va inserito come primo messaggio nella conversazione.

from transformers import AutoModelForCausalLM, AutoProcessor

# Caricamento modello
phi_model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3.5-vision-instruct",
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True,
    _attn_implementation="eager"   # necessario su T4 per evitare errori di attenzione
)
phi_proc = AutoProcessor.from_pretrained(
    "microsoft/Phi-3.5-vision-instruct",
    trust_remote_code=True
)


def infer_phi(image_path, prompt, max_new_tokens):
    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    # Phi richiede il placeholder <|image_1|> nel testo per indicare dove va l'immagine.
    # Il system message viene inserito come primo messaggio separato.
    messages = [
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user",   "content": f"<|image_1|>\n{prompt}"}
    ]

    # Applica il template di Phi e tokenizza
    text   = phi_proc.tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = phi_proc(text, [img], return_tensors="pt").to(phi_model.device)

    # Genera la risposta (solo i token nuovi)
    with torch.no_grad():
        output_ids = phi_model.generate(**inputs, max_new_tokens=max_new_tokens)

    new_tokens = output_ids[0][inputs["input_ids"].shape[-1]:]
    return phi_proc.decode(new_tokens, skip_special_tokens=True)


predictions_phi = run_inference(infer_phi, "phi35_vision")
free_vram("phi_model", "phi_proc")

"""## VALUTAZIONE E ANALISI (BASELINE)

Calcolo le metriche di classificazione (accuracy, precision, recall, F1) per
ciascun modello, sia globalmente sia per tipo di corruzione, e visualizzo le
confusion matrix per confrontare i tre modelli sulla baseline.
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix
)

# Classe positiva = unanswerable (quella che vogliamo rilevare)
POS = "unanswerable"
NEG = "answerable"


def evaluate(predictions, model_name):
    """
    Calcola le metriche di classificazione per un modello.
    Restituisce un dizionario con accuracy, precision, recall, F1
    globali e F1 per tipo di corruzione.
    """
    y_true = [p["label"]      for p in predictions]
    y_pred = [p["prediction"] for p in predictions]

    # ── Metriche per tipo di corruzione ──
    # Per le corrotte (entity/element/layout): F1 sulla classe unanswerable
    # Per le clean: accuracy (non ha senso F1 su una classe assente)
    per_type = {}
    corruption_types = sorted({p["corruption_type"] for p in predictions})

    for ctype in corruption_types:
        subset  = [p for p in predictions if p["corruption_type"] == ctype]
        yt      = [p["label"]      for p in subset]
        yp      = [p["prediction"] for p in subset]

        if ctype == "clean":
            per_type[ctype] = accuracy_score(yt, yp)
        else:
            per_type[ctype] = f1_score(
                yt, yp,
                pos_label=POS,
                labels=[NEG, POS],
                zero_division=0
            )

    return {
        "model"      : model_name,
        "acc"        : accuracy_score(y_true, y_pred),
        "prec"       : precision_score(y_true, y_pred, pos_label=POS, zero_division=0),
        "rec"        : recall_score(y_true, y_pred,    pos_label=POS, zero_division=0),
        "f1"         : f1_score(y_true, y_pred,        pos_label=POS, zero_division=0),
        "f1_macro"   : f1_score(y_true, y_pred, average="macro",      zero_division=0),
        "cm"         : confusion_matrix(y_true, y_pred, labels=[NEG, POS]),
        "parse_fail" : sum(p.get("parse_fail", False) for p in predictions),
        "per_type"   : per_type,
    }


# ── Carica tutti i JSON di predizione e calcola le metriche ──
all_metrics = {}

for fname in sorted(os.listdir(PRED_DIR)):
    if not (fname.startswith("predictions_") and fname.endswith(".json")):
        continue

    model_name = fname[len("predictions_"):-len(".json")]

    with open(os.path.join(PRED_DIR, fname)) as f:
        predictions = json.load(f)

    all_metrics[model_name] = evaluate(predictions, model_name)


# ── Tabella 1: metriche globali ──
print(f"\n{'Modello':<26} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6} {'F1-mac':>7} {'fail':>5}")
print("─" * 68)
for name, m in all_metrics.items():
    print(
        f"{name:<26} "
        f"{m['acc']:>6.3f} "
        f"{m['prec']:>6.3f} "
        f"{m['rec']:>6.3f} "
        f"{m['f1']:>6.3f} "
        f"{m['f1_macro']:>7.3f} "
        f"{m['parse_fail']:>5d}"
    )

# ── Tabella 2: F1 per tipo di corruzione ──
CTYPES = ["entity", "element", "layout", "clean"]

print(f"\n{'F1 per tipo (clean = accuracy)'}")
print(f"{'Modello':<26}" + "".join(f"{c:>10}" for c in CTYPES))
print("─" * 66)
for name, m in all_metrics.items():
    row = "".join(
        f"{m['per_type'].get(c, float('nan')):>10.3f}"
        for c in CTYPES
    )
    print(f"{name:<26}{row}")

import json
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score
)

# ── Config ────────────────────────────────────────────────────────────────────
PRED_DIR = "/content/drive/MyDrive/docvqa/predictions"
POS      = "unanswerable"
NEG      = "answerable"
CTYPES   = ["entity", "element", "layout", "clean"]

# ── Funzione di valutazione ───────────────────────────────────────────────────
def evaluate(fname):
    with open(os.path.join(PRED_DIR, fname)) as f:
        preds = json.load(f)

    y_true = [p["label"]      for p in preds]
    y_pred = [p["prediction"] for p in preds]

    per_type = {}
    for ctype in CTYPES:
        subset = [p for p in preds if p["corruption_type"] == ctype]
        if not subset:
            continue
        yt = [p["label"]      for p in subset]
        yp = [p["prediction"] for p in subset]
        if ctype == "clean":
            per_type[ctype] = accuracy_score(yt, yp)
        else:
            per_type[ctype] = f1_score(yt, yp, pos_label=POS,
                                       labels=[NEG, POS], zero_division=0)

    return {
        "acc"     : accuracy_score(y_true, y_pred),
        "prec"    : precision_score(y_true, y_pred, pos_label=POS, zero_division=0),
        "rec"     : recall_score(y_true, y_pred,    pos_label=POS, zero_division=0),
        "f1"      : f1_score(y_true, y_pred,        pos_label=POS, zero_division=0),
        "fail"    : sum(p.get("parse_fail", False) for p in preds),
        "per_type": per_type,
    }

# ── File baseline da caricare ─────────────────────────────────────────────────
baseline_files = {
    "Qwen2-VL-2B"   : "predictions_qwen2vl_2b.json",
    "Gemma3-4B"     : "predictions_gemma3_4b.json",
    "Phi3.5-Vision" : "predictions_phi35_vision.json",
}

models   = []
metrics  = {}
per_type = {}

for display_name, fname in baseline_files.items():
    path = os.path.join(PRED_DIR, fname)
    if not os.path.isfile(path):
        print(f"[SKIP] non trovato: {fname}")
        continue
    m = evaluate(fname)
    models.append(display_name)
    metrics[display_name]  = m
    per_type[display_name] = m["per_type"]
    print(f"[OK] {display_name}: acc={m['acc']:.3f}  prec={m['prec']:.3f}  "
          f"rec={m['rec']:.3f}  f1={m['f1']:.3f}  fail={m['fail']}")

# ── Colori ────────────────────────────────────────────────────────────────────
COLOR_MAP = {
    "Qwen2-VL-2B"   : "#2ecc71",
    "Gemma3-4B"     : "#e67e22",
    "Phi3.5-Vision" : "#c0392b",
}
colors = [COLOR_MAP[m] for m in models]

# ══════════════════════════════════════════════════════════════════════════════
# FIGURA — F1 per tipo di corruzione
# ══════════════════════════════════════════════════════════════════════════════
clabels = ["entity", "element", "layout", "clean (acc)"]
x       = np.arange(len(CTYPES))
bar_w   = 0.22
n       = len(models)

fig, ax = plt.subplots(figsize=(11, 5))

for i, (model, color) in enumerate(zip(models, colors)):
    vals   = [per_type[model].get(k, 0.0) for k in CTYPES]
    offset = (i - (n - 1) / 2) * bar_w
    ax.bar(x + offset, vals, width=bar_w, color=color,
           alpha=0.88, label=model, zorder=3)

ax.set_ylim(0, 1.05)
ax.set_xticks(x)
ax.set_xticklabels(clabels, fontsize=11)
ax.set_ylabel("F1 / Accuracy", fontsize=11)
ax.set_title("F1 per tipo di corruzione", fontsize=13, fontweight="bold", pad=12)
ax.yaxis.set_major_locator(plt.MultipleLocator(0.2))
ax.yaxis.grid(True, linestyle="--", alpha=0.5, zorder=0)
ax.set_axisbelow(True)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

patches = [mpatches.Patch(color=COLOR_MAP[m], label=m) for m in models]
ax.legend(handles=patches, fontsize=10, loc="upper right",
          framealpha=0.9, edgecolor="#ddd")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/docvqa/F1CorruzioneSP.png", dpi=200, bbox_inches="tight")
plt.show()

# ── Confusion matrix per tutti i modelli ──
models = list(all_metrics.keys())
n = len(models)

fig, axes = plt.subplots(1, n, figsize=(3.5 * n, 3.5))
if n == 1:
    axes = [axes]

for ax, name in zip(axes, models):
    m  = all_metrics[name]
    cm = m["cm"]

    im = ax.imshow(cm, cmap="Blues")

    # valori nelle celle
    for i in range(2):
        for j in range(2):
            ax.text(j, i, cm[i, j],
                    ha="center", va="center", fontsize=12,
                    color="white" if cm[i, j] > cm.max() / 2 else "black")

    ax.set_xticks([0, 1])
    ax.set_xticklabels([NEG, POS], rotation=45, ha="right", fontsize=8)
    ax.set_yticks([0, 1])
    ax.set_yticklabels([NEG, POS], fontsize=8)
    ax.set_xlabel("Predicted", fontsize=8)
    ax.set_ylabel("True", fontsize=8)
    ax.set_title(f"{name}\nAcc={m['acc']:.2f}  F1={m['f1']:.2f}  Rec={m['rec']:.2f}", fontsize=8)

plt.suptitle("Confusion matrices — tutti i modelli", fontsize=11, y=1.02)
plt.tight_layout()
plt.show()

"""## PARTE 3 — MITIGAZIONE IN-CONTEXT

Applico tre strategie di mitigazione in-context (senza fine-tuning) a tutti
e tre i modelli: few-shot (due esempi nel prompt), Chain-of-Thought
(ragionamento step-by-step) e knowledge injection (checklist esplicita di
cosa verificare nel documento). Inizio da Qwen.
"""

pip install "transformers>=4.52" qwen-vl-utils -q

# ══════════════════════════════════════════════════════════════
# PARTE 3 — Mitigazione Qwen2-VL-2B
# Esegui dopo: Setup globale + Utilities + build_prompt
# ══════════════════════════════════════════════════════════════

# ── Caricamento modello ──
from transformers import Qwen2VLForConditionalGeneration, AutoProcessor

qwen_model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    torch_dtype=torch.float16,
    device_map="auto"
)
qwen_proc = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct")

# ── Funzione di inferenza ──
def infer_qwen(image_path, prompt, max_new_tokens):

    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    messages = [
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user", "content": [
            {"type": "image", "image": img},
            {"type": "text",  "text": prompt}
        ]}
    ]

    text = qwen_proc.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = qwen_proc(
        text=[text],
        images=[img],
        return_tensors="pt"
    ).to(qwen_model.device)

    with torch.no_grad():
        output_ids = qwen_model.generate(**inputs, max_new_tokens=max_new_tokens)

    new_tokens = output_ids[0][inputs["input_ids"].shape[-1]:]
    return qwen_proc.decode(new_tokens, skip_special_tokens=True)


# ── Inferenza per ogni strategia di mitigazione ──
# Produce tre file su Drive:
#   predictions_qwen2vl_2b_few_shot.json
#   predictions_qwen2vl_2b_cot.json
#   predictions_qwen2vl_2b_knowledge.json

for strategy in ["few_shot", "cot", "knowledge"]:
    print(f"\n{'═'*50}")
    print(f"  Strategia: {strategy.upper()}")
    print(f"{'═'*50}")
    run_inference(infer_qwen, "qwen2vl_2b", strategy=strategy)

# ── Libera VRAM prima della sessione successiva ──
free_vram("qwen_model", "qwen_proc")

"""## MITIGAZIONE GEMMA

Stessa procedura della Parte 3, applicata a Gemma-3-4B.
"""

pip install "transformers>=4.50" -q

# ══════════════════════════════════════════════════════════════
# PARTE 3 — Mitigazione Gemma3-4B
# Esegui dopo: Setup globale + Utilities + build_prompt
# ══════════════════════════════════════════════════════════════

# ── Caricamento modello ──
from huggingface_hub import login
from google.colab import userdata
from transformers import pipeline

login(token=userdata.get('HF_TOKEN'))

pipe_gemma = pipeline(
    "image-text-to-text",
    model="google/gemma-3-4b-it",
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

# ── Funzione di inferenza ──
def infer_gemma(image_path, prompt, max_new_tokens):
    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    messages = [
        {"role": "system", "content": [{"type": "text", "text": SYSTEM_MESSAGE}]},
        {"role": "user",   "content": [
            {"type": "image", "image": img},
            {"type": "text",  "text": prompt}
        ]}
    ]

    out = pipe_gemma(messages, max_new_tokens=max_new_tokens)
    return out[0]["generated_text"][-1]["content"]


# ── Inferenza per ogni strategia di mitigazione ──
# Produce tre file su Drive:
#   predictions_gemma3_4b_few_shot.json
#   predictions_gemma3_4b_cot.json
#   predictions_gemma3_4b_knowledge.json

for strategy in ["few_shot", "cot", "knowledge"]:
    print(f"\n{'═'*50}")
    print(f"  Strategia: {strategy.upper()}")
    print(f"{'═'*50}")
    run_inference(infer_gemma, "gemma3_4b", strategy=strategy)

# ── Libera VRAM prima della sessione successiva ──
free_vram("pipe_gemma")

"""## MITIGAZIONE PHI 3.5

Stessa procedura della Parte 3, applicata a Phi-3.5-vision (sessione
separata per la versione di transformers).
"""

pip install "transformers==4.48.0"

# ══════════════════════════════════════════════════════════════
# PARTE 3 — Mitigazione Phi3.5-Vision
# Esegui dopo: Setup globale + Utilities + build_prompt
# pip install "transformers==4.48.0" -q → restart → Setup → Utilities
# ══════════════════════════════════════════════════════════════

# ── Caricamento modello ──
from transformers import AutoModelForCausalLM, AutoProcessor

phi_model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3.5-vision-instruct",
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True,
    _attn_implementation="eager"
)
phi_proc = AutoProcessor.from_pretrained(
    "microsoft/Phi-3.5-vision-instruct",
    trust_remote_code=True
)

# ── Funzione di inferenza ──
def infer_phi(image_path, prompt, max_new_tokens):
    img = Image.open(image_path).convert("RGB")
    img.thumbnail((512, 512))

    messages = [
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user",   "content": f"<|image_1|>\n{prompt}"}
    ]

    text = phi_proc.tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = phi_proc(text, [img], return_tensors="pt").to(phi_model.device)

    with torch.no_grad():
        output_ids = phi_model.generate(**inputs, max_new_tokens=max_new_tokens)

    new_tokens = output_ids[0][inputs["input_ids"].shape[-1]:]
    return phi_proc.decode(new_tokens, skip_special_tokens=True)


# ── Inferenza per ogni strategia di mitigazione ──
# Produce tre file su Drive:
#   predictions_phi35_vision_few_shot.json
#   predictions_phi35_vision_cot.json
#   predictions_phi35_vision_knowledge.json

for strategy in ["few_shot", "cot", "knowledge"]:
    print(f"\n{'═'*50}")
    print(f"  Strategia: {strategy.upper()}")
    print(f"{'═'*50}")
    run_inference(infer_phi, "phi35_vision", strategy=strategy)

# ── Libera VRAM prima della sessione successiva ──
free_vram("phi_model", "phi_proc")

"""## VALUTAZIONE METRICHE IN-CONTEXT LEARNING

Confronto le metriche di tutte le strategie (baseline, few-shot, CoT,
knowledge) sui tre modelli, per capire quale mitigazione funziona meglio e
su quali tipi di corruzione.
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix
)

# Classe positiva = unanswerable (quella che vogliamo rilevare)
POS = "unanswerable"
NEG = "answerable"


def evaluate(predictions, model_name):
    """
    Calcola le metriche di classificazione per un modello.
    Restituisce un dizionario con accuracy, precision, recall, F1
    globali e F1 per tipo di corruzione.
    """
    y_true = [p["label"]      for p in predictions]
    y_pred = [p["prediction"] for p in predictions]

    # ── Metriche per tipo di corruzione ──
    # Per le corrotte (entity/element/layout): F1 sulla classe unanswerable
    # Per le clean: accuracy (non ha senso F1 su una classe assente)
    per_type = {}
    corruption_types = sorted({p["corruption_type"] for p in predictions})

    for ctype in corruption_types:
        subset  = [p for p in predictions if p["corruption_type"] == ctype]
        yt      = [p["label"]      for p in subset]
        yp      = [p["prediction"] for p in subset]

        if ctype == "clean":
            per_type[ctype] = accuracy_score(yt, yp)
        else:
            per_type[ctype] = f1_score(
                yt, yp,
                pos_label=POS,
                labels=[NEG, POS],
                zero_division=0
            )

    return {
        "model"      : model_name,
        "acc"        : accuracy_score(y_true, y_pred),
        "prec"       : precision_score(y_true, y_pred, pos_label=POS, zero_division=0),
        "rec"        : recall_score(y_true, y_pred,    pos_label=POS, zero_division=0),
        "f1"         : f1_score(y_true, y_pred,        pos_label=POS, zero_division=0),
        "f1_macro"   : f1_score(y_true, y_pred, average="macro",      zero_division=0),
        "cm"         : confusion_matrix(y_true, y_pred, labels=[NEG, POS]),
        "parse_fail" : sum(p.get("parse_fail", False) for p in predictions),
        "per_type"   : per_type,
    }


# ── Carica tutti i JSON di predizione e calcola le metriche ──
all_metrics = {}

for fname in sorted(os.listdir(PRED_DIR)):
    if not (fname.startswith("predictions_") and fname.endswith(".json")):
        continue

    model_name = fname[len("predictions_"):-len(".json")]

    with open(os.path.join(PRED_DIR, fname)) as f:
        predictions = json.load(f)

    all_metrics[model_name] = evaluate(predictions, model_name)


# ── Tabella 1: metriche globali ──
print(f"\n{'Modello':<26} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6} {'F1-mac':>7} {'fail':>5}")
print("─" * 68)
for name, m in all_metrics.items():
    print(
        f"{name:<26} "
        f"{m['acc']:>6.3f} "
        f"{m['prec']:>6.3f} "
        f"{m['rec']:>6.3f} "
        f"{m['f1']:>6.3f} "
        f"{m['f1_macro']:>7.3f} "
        f"{m['parse_fail']:>5d}"
    )

# ── Tabella 2: F1 per tipo di corruzione ──
CTYPES = ["entity", "element", "layout", "clean"]

print(f"\n{'F1 per tipo (clean = accuracy)'}")
print(f"{'Modello':<26}" + "".join(f"{c:>10}" for c in CTYPES))
print("─" * 66)
for name, m in all_metrics.items():
    row = "".join(
        f"{m['per_type'].get(c, float('nan')):>10.3f}"
        for c in CTYPES
    )
    print(f"{name:<26}{row}")

# ── Confusion matrix — griglia automatica a righe da 4 ──
models = list(all_metrics.keys())
n = len(models)
n_cols = 4
n_rows = (n + n_cols - 1) // n_cols  # arrotonda su

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * n_cols, 4 * n_rows))
axes = axes.flatten()

for idx, name in enumerate(models):
    ax = axes[idx]
    m  = all_metrics[name]
    cm = m["cm"]

    ax.imshow(cm, cmap="Blues")

    for i in range(2):
        for j in range(2):
            ax.text(j, i, cm[i, j],
                    ha="center", va="center", fontsize=11,
                    color="white" if cm[i, j] > cm.max() / 2 else "black")

    ax.set_xticks([0, 1])
    ax.set_xticklabels([NEG, POS], rotation=45, ha="right", fontsize=7)
    ax.set_yticks([0, 1])
    ax.set_yticklabels([NEG, POS], fontsize=7)
    ax.set_xlabel("Predicted", fontsize=7)
    ax.set_ylabel("True", fontsize=7)
    ax.set_title(
        f"{name}\nAcc={m['acc']:.2f}  F1={m['f1']:.2f}  Rec={m['rec']:.2f}",
        fontsize=8
    )

# Nasconde i subplot vuoti
for idx in range(n, len(axes)):
    axes[idx].axis("off")

plt.suptitle("Confusion matrices — tutti i modelli", fontsize=13, y=1.01)
plt.tight_layout()
plt.show()

"""## ANALISI PROMPT E OUTPUT

Ispezione qualitativa: prendo lo stesso campione e confronto prompt e output
grezzo del modello tra le diverse strategie, per capire concretamente cosa
cambia nel comportamento del modello.
"""

import json
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score
)

# ── Config ────────────────────────────────────────────────────────────────────
PRED_DIR = "/content/drive/MyDrive/docvqa/predictions"
POS      = "unanswerable"
NEG      = "answerable"
CTYPES   = ["entity", "element", "layout", "clean"]

# ── Funzione di valutazione ───────────────────────────────────────────────────
def evaluate(fname):
    path = os.path.join(PRED_DIR, fname)
    if not os.path.isfile(path):
        return None
    with open(path) as f:
        preds = json.load(f)

    y_true = [p["label"]      for p in preds]
    y_pred = [p["prediction"] for p in preds]

    per_type = {}
    for ctype in CTYPES:
        subset = [p for p in preds if p["corruption_type"] == ctype]
        if not subset:
            continue
        yt = [p["label"]      for p in subset]
        yp = [p["prediction"] for p in subset]
        if ctype == "clean":
            per_type[ctype] = accuracy_score(yt, yp)
        else:
            per_type[ctype] = f1_score(yt, yp, pos_label=POS,
                                       labels=[NEG, POS], zero_division=0)
    return {
        "acc"     : accuracy_score(y_true, y_pred),
        "prec"    : precision_score(y_true, y_pred, pos_label=POS, zero_division=0),
        "rec"     : recall_score(y_true, y_pred,    pos_label=POS, zero_division=0),
        "f1"      : f1_score(y_true, y_pred,        pos_label=POS, zero_division=0),
        "per_type": per_type,
    }

# ── File da caricare ──────────────────────────────────────────────────────────
# Struttura: { nome_display: { strategia: nome_file } }
FILES = {
    "Gemma3-4B": {
        "baseline" : "predictions_gemma3_4b.json",
        "few_shot" : "predictions_gemma3_4b_few_shot.json",
        "cot"      : "predictions_gemma3_4b_cot.json",
        "knowledge": "predictions_gemma3_4b_knowledge.json",
    },
    "Phi3.5-Vision": {
        "baseline" : "predictions_phi35_vision.json",
        "few_shot" : "predictions_phi35_vision_few_shot.json",
        "cot"      : "predictions_phi35_vision_cot.json",
        "knowledge": "predictions_phi35_vision_knowledge.json",
    },
    "Qwen2-VL-2B": {
        "baseline" : "predictions_qwen2vl_2b.json",
        "few_shot" : "predictions_qwen2vl_2b_few_shot.json",
        "cot"      : "predictions_qwen2vl_2b_cot.json",
        "knowledge": "predictions_qwen2vl_2b_knowledge.json",
    },
}

STRATEGIES   = ["baseline", "few_shot", "cot", "knowledge"]
STRAT_LABELS = ["Baseline", "Few-shot", "CoT", "Knowledge"]
MODELS       = list(FILES.keys())

COLOR_MAP = {
    "Qwen2-VL-2B"   : "#2ecc71",
    "Gemma3-4B"     : "#e67e22",
    "Phi3.5-Vision" : "#c0392b",
}
COLORS_STRAT = ["#555555", "#3498db", "#e74c3c", "#2ecc71"]

# ── Carica tutti i risultati ──────────────────────────────────────────────────
data = {}
for model, strat_files in FILES.items():
    data[model] = {}
    for strat, fname in strat_files.items():
        result = evaluate(fname)
        if result is None:
            print(f"[SKIP] {fname} non trovato")
        else:
            data[model][strat] = result
            print(f"[OK] {model} / {strat}: f1={result['f1']:.3f}")

# ══════════════════════════════════════════════════════════════════════════════
# FIG 1 — F1 per modello e strategia (grouped bar)
# ══════════════════════════════════════════════════════════════════════════════
fig, ax = plt.subplots(figsize=(10, 4.5))

x     = np.arange(len(MODELS))
bar_w = 0.18

for i, (strat, label, color) in enumerate(zip(STRATEGIES, STRAT_LABELS, COLORS_STRAT)):
    vals   = [data[m][strat]["f1"] if strat in data[m] else 0 for m in MODELS]
    offset = (i - 1.5) * bar_w
    bars   = ax.bar(x + offset, vals, width=bar_w, color=color,
                    alpha=0.88, label=label, zorder=3)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.01,
                f"{val:.2f}", ha="center", va="bottom", fontsize=7.5)

ax.set_xticks(x)
ax.set_xticklabels(MODELS, fontsize=11)
ax.set_ylim(0, 0.85)
ax.set_ylabel("F1 (unanswerable)", fontsize=11)
ax.set_title("F1 per modello e strategia", fontsize=13, fontweight="bold", pad=10)
ax.yaxis.grid(True, linestyle="--", alpha=0.4, zorder=0)
ax.set_axisbelow(True)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.legend(fontsize=9, loc="upper left", framealpha=0.9)

plt.tight_layout()
plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# FIG 2 — Precision vs Recall (scatter con frecce dal baseline)
# ══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))
fig.suptitle("Precision vs Recall — effetto delle mitigazioni",
             fontsize=13, fontweight="bold", y=1.01)

markers = {"baseline": "o", "few_shot": "s", "cot": "^", "knowledge": "D"}
msizes  = {"baseline": 90,  "few_shot": 70,  "cot": 70,  "knowledge": 70}

for ax, model in zip(axes, MODELS):
    color  = COLOR_MAP[model]
    base_p = data[model]["baseline"]["prec"]
    base_r = data[model]["baseline"]["rec"]

    for strat, label in zip(STRATEGIES, STRAT_LABELS):
        if strat not in data[model]:
            continue
        p = data[model][strat]["prec"]
        r = data[model][strat]["rec"]

        ax.scatter(r, p, s=msizes[strat], color=color,
                   marker=markers[strat], zorder=4,
                   alpha=1.0 if strat == "baseline" else 0.75,
                   edgecolors="black" if strat == "baseline" else "none",
                   linewidths=1.2)

        if strat != "baseline":
            ax.annotate("", xy=(r, p), xytext=(base_r, base_p),
                        arrowprops=dict(arrowstyle="->", color=color,
                                        lw=1.2, alpha=0.6))
        ax.text(r + 0.01, p + 0.008, label[:3], fontsize=7.5, color="#333")

    ax.set_xlim(0, 1.05)
    ax.set_ylim(0.45, 1.05)
    ax.set_xlabel("Recall", fontsize=10)
    ax.set_ylabel("Precision", fontsize=10)
    ax.set_title(model, fontsize=11, fontweight="bold")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

handles = [
    plt.scatter([], [], s=msizes[s], color="gray", marker=markers[s],
                label=l, edgecolors="black" if s == "baseline" else "none",
                linewidths=1.2)
    for s, l in zip(STRATEGIES, STRAT_LABELS)
]
fig.legend(handles=handles, fontsize=9, loc="lower center",
           ncol=4, bbox_to_anchor=(0.5, -0.08), framealpha=0.9)

plt.tight_layout()
plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# FIG 3 — Heatmap F1 per tipo di corruzione
# ══════════════════════════════════════════════════════════════════════════════
# Etichette righe: Gemma/base, Gemma/few, ...
short_name = {"Gemma3-4B": "Gemma", "Phi3.5-Vision": "Phi", "Qwen2-VL-2B": "Qwen"}
strat_abbr = {"baseline": "base", "few_shot": "few", "cot": "cot", "knowledge": "know"}

row_labels = [f"{short_name[m]}/{strat_abbr[s]}"
              for m in MODELS for s in STRATEGIES]

matrix = np.array([
    [data[m][s]["per_type"].get(c, 0.0) if s in data[m] else 0.0
     for c in CTYPES]
    for m in MODELS for s in STRATEGIES
])

fig, axes = plt.subplots(1, 4, figsize=(14, 4.5))
fig.suptitle("F1 per tipo di corruzione — baseline vs mitigazioni",
             fontsize=13, fontweight="bold", y=1.01)

for col_idx, (ax, ctype) in enumerate(zip(axes, CTYPES)):
    col_vals = matrix[:, col_idx].reshape(-1, 1)
    im = ax.imshow(col_vals, aspect="auto", cmap="RdYlGn", vmin=0, vmax=1)

    ax.set_xticks([])
    ax.set_yticks(range(len(row_labels)))

    if col_idx == 0:
        ax.set_yticklabels(row_labels, fontsize=8.5)
    else:
        ax.set_yticklabels([])

    ax.set_title(ctype, fontsize=10, fontweight="bold")

    for row_idx in range(len(row_labels)):
        val = col_vals[row_idx, 0]
        text_color = "black" if 0.25 < val < 0.75 else "white"
        ax.text(0, row_idx, f"{val:.2f}", ha="center", va="center",
                fontsize=8.5, color=text_color)

    # Linea bianca separatrice tra modelli (dopo riga 3 e 7)
    for sep in [3.5, 7.5]:
        ax.axhline(sep, color="white", linewidth=2.5)

plt.colorbar(im, ax=axes[-1], fraction=0.08, pad=0.04)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

fig, ax = plt.subplots(figsize=(9.2, 4.3))
ax.set_xlim(0, 10.3)
ax.set_ylim(1.0, 4.8)
ax.axis("off")

BOX_KWARGS = dict(boxstyle="round,pad=0.22", linewidth=1.3)

def box(ax, x, y, w, h, fc, ec, title, lines, title_color="black"):
    rect = mpatches.FancyBboxPatch((x - w/2, y - h/2), w, h,
                                    facecolor=fc, edgecolor=ec, **BOX_KWARGS)
    ax.add_patch(rect)
    top_edge = y + h/2
    title_y = top_edge - 0.30
    ax.text(x, title_y, title,
            fontsize=13, fontweight="bold", ha="center", va="center", color=title_color)
    line_y = title_y - 0.34
    for i, line in enumerate(lines):
        ax.text(x, line_y - i*0.30, line,
                fontsize=10.5, ha="center", va="center", color="#444444")

def arrow(ax, x1, y1, x2, y2, label="", lx=0, ly=0.12):
    ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="-|>", color="#555555", lw=1.3))
    if label:
        ax.text((x1+x2)/2 + lx, (y1+y2)/2 + ly, label,
                fontsize=9.5, color="#555555", ha="center")

# ── Colonna sinistra: input ──
box(ax, 1.6, 4.0, 2.6, 1.15,
    fc="#dce9f7", ec="#4a7ab5",
    title="Immagine", title_color="#1a4f8a",
    lines=["documento .png/.jpg", "(PIL Image)"])

box(ax, 1.6, 2.4, 2.6, 1.45,
    fc="#d6f0e0", ec="#3a7d56",
    title="Prompt (testo)", title_color="#1f5c3a",
    lines=["istruzione + strategia", "+ domanda", "build_prompt()"])

# ── Colonna centro: modello ──
box(ax, 5.1, 3.0, 2.4, 1.30,
    fc="#e8e4f7", ec="#6258a8",
    title="Modello", title_color="#3b2f8f",
    lines=["Gemma / Qwen / Phi", "multimodale"])

# ── Colonna destra: output → normalize ──
box(ax, 8.7, 4.0, 2.3, 0.85,
    fc="#fef3dc", ec="#b8860b",
    title="Output grezzo", title_color="#7a5800",
    lines=["testo libero"])

box(ax, 8.7, 2.85, 2.3, 0.85,
    fc="#fde0dc", ec="#b84a3a",
    title="normalize_pred()", title_color="#8b1a0e",
    lines=["ANSWERABLE / UNANSWERABLE"])

# ── Parse fail: ramo condizionale ──
box(ax, 8.7, 1.725, 2.3, 0.80,
    fc="#f0f0f0", ec="#999999",
    title="Parse fail", title_color="#666666",
    lines=["→ ANSWERABLE (default)"])

# ── Frecce ──
arrow(ax, 2.9, 4.0, 3.9, 3.35, label="PIL image", lx=0.25, ly=0.15)
arrow(ax, 2.9, 2.4, 3.9, 2.65, label="str", lx=0.2, ly=-0.15)
arrow(ax, 6.3, 3.35, 7.55, 3.85, label="str", lx=0.15, ly=0.15)
arrow(ax, 8.7, 3.575, 8.7, 3.275)

ax.annotate("", xy=(8.7, 2.125), xytext=(8.7, 2.425),
            arrowprops=dict(arrowstyle="-|>", color="#999999",
                            lw=1.1, linestyle="dashed"))
ax.text(9.05, 2.27, "se parse fail", fontsize=9,
        color="#888888", style="italic", ha="left")

ax.set_title("Input al modello per ogni campione",
             fontsize=15, fontweight="bold", pad=10)

plt.tight_layout()
plt.savefig("pipeline_input.png", dpi=220, bbox_inches="tight")
plt.show()